### ISSUE TITLE
Wont work on servers

### ISSUE THREAD

**Issue by ShazerHD** [TyrellPlayz/TyrellPlayz-City-Mod#1]
When I try to open the GUI of the traffic box, I get this error:

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.tyrellplayz.tcm.blocks.BlockTrafficBoxBottom.openGui(BlockTrafficBoxBottom.java:73) ~[BlockTrafficBoxBottom.class:?]
        at com.tyrellplayz.tcm.blocks.BlockTrafficBoxBottom.func_180639_a(BlockTrafficBoxBottom.java:117) ~[BlockTrafficBoxBottom.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by TyrellPlayz** [comment]
Fixed
